/**
 * VDock selectable visuals — generated by `npm run visuals:encode`.
 * Masters live in `Vizualz/`; encoded assets in `public/vdock/visuals/`.
 */

export interface VdockVisual {
  id: string;
  title: string;
  previewUrl: string;
  loopWebm: string;
  loopMp4: string;
}

export const VDOCK_VISUALS: VdockVisual[] = [
  {
    id: "vizual-02",
    title: "Vizual 02",
    previewUrl: "/vdock/visuals/vizual-02/preview.webp",
    loopWebm: "/vdock/visuals/vizual-02/loop.webm",
    loopMp4: "/vdock/visuals/vizual-02/loop.mp4",
  },
  {
    id: "vizual-03",
    title: "Vizual 03",
    previewUrl: "/vdock/visuals/vizual-03/preview.webp",
    loopWebm: "/vdock/visuals/vizual-03/loop.webm",
    loopMp4: "/vdock/visuals/vizual-03/loop.mp4",
  },
  {
    id: "vizual-03b",
    title: "Vizual 03B",
    previewUrl: "/vdock/visuals/vizual-03b/preview.webp",
    loopWebm: "/vdock/visuals/vizual-03b/loop.webm",
    loopMp4: "/vdock/visuals/vizual-03b/loop.mp4",
  },
  {
    id: "vizual-04",
    title: "Vizual 04",
    previewUrl: "/vdock/visuals/vizual-04/preview.webp",
    loopWebm: "/vdock/visuals/vizual-04/loop.webm",
    loopMp4: "/vdock/visuals/vizual-04/loop.mp4",
  },
  {
    id: "vizual-04b",
    title: "Vizual 04B",
    previewUrl: "/vdock/visuals/vizual-04b/preview.webp",
    loopWebm: "/vdock/visuals/vizual-04b/loop.webm",
    loopMp4: "/vdock/visuals/vizual-04b/loop.mp4",
  },
  {
    id: "vizual-05",
    title: "Vizual 05",
    previewUrl: "/vdock/visuals/vizual-05/preview.webp",
    loopWebm: "/vdock/visuals/vizual-05/loop.webm",
    loopMp4: "/vdock/visuals/vizual-05/loop.mp4",
  },
  {
    id: "vizual-06",
    title: "Vizual 06",
    previewUrl: "/vdock/visuals/vizual-06/preview.webp",
    loopWebm: "/vdock/visuals/vizual-06/loop.webm",
    loopMp4: "/vdock/visuals/vizual-06/loop.mp4",
  },
  {
    id: "vizual-07",
    title: "Vizual 07",
    previewUrl: "/vdock/visuals/vizual-07/preview.webp",
    loopWebm: "/vdock/visuals/vizual-07/loop.webm",
    loopMp4: "/vdock/visuals/vizual-07/loop.mp4",
  },
  {
    id: "vizual-08",
    title: "Vizual 08",
    previewUrl: "/vdock/visuals/vizual-08/preview.webp",
    loopWebm: "/vdock/visuals/vizual-08/loop.webm",
    loopMp4: "/vdock/visuals/vizual-08/loop.mp4",
  },
  {
    id: "vizual-09",
    title: "Vizual 09",
    previewUrl: "/vdock/visuals/vizual-09/preview.webp",
    loopWebm: "/vdock/visuals/vizual-09/loop.webm",
    loopMp4: "/vdock/visuals/vizual-09/loop.mp4",
  },
  {
    id: "vizual-10",
    title: "Vizual 10",
    previewUrl: "/vdock/visuals/vizual-10/preview.webp",
    loopWebm: "/vdock/visuals/vizual-10/loop.webm",
    loopMp4: "/vdock/visuals/vizual-10/loop.mp4",
  },
  {
    id: "vizual-11",
    title: "Vizual 11",
    previewUrl: "/vdock/visuals/vizual-11/preview.webp",
    loopWebm: "/vdock/visuals/vizual-11/loop.webm",
    loopMp4: "/vdock/visuals/vizual-11/loop.mp4",
  },
  {
    id: "vizual-12",
    title: "Vizual 12",
    previewUrl: "/vdock/visuals/vizual-12/preview.webp",
    loopWebm: "/vdock/visuals/vizual-12/loop.webm",
    loopMp4: "/vdock/visuals/vizual-12/loop.mp4",
  },
  {
    id: "vizual-13",
    title: "Vizual 13",
    previewUrl: "/vdock/visuals/vizual-13/preview.webp",
    loopWebm: "/vdock/visuals/vizual-13/loop.webm",
    loopMp4: "/vdock/visuals/vizual-13/loop.mp4",
  }
];

export function vdockVisual(id: string | undefined | null): VdockVisual | undefined {
  if (!id) return undefined;
  return VDOCK_VISUALS.find((v) => v.id === id);
}
