/**
 * VDock selectable visuals — generated by `npm run visuals:encode`.
 * Masters live in `vizualz/`; encoded assets in `public/vdock/visuals/`
 * and served from the public Supabase bucket `site-visuals` in production.
 */

import { siteVisualUrl } from "@/lib/siteVisuals";

export interface VdockVisual {
  id: string;
  title: string;
  previewUrl: string;
  loopWebm: string;
  loopMp4: string;
}

function visual(id: string, title: string): VdockVisual {
  const base = `vdock/visuals/${id}`;
  return {
    id,
    title,
    previewUrl: siteVisualUrl(`${base}/preview.webp`),
    loopWebm: siteVisualUrl(`${base}/loop.webm`),
    loopMp4: siteVisualUrl(`${base}/loop.mp4`),
  };
}

export const VDOCK_VISUALS: VdockVisual[] = [
  visual("vizual-02", "Vizual 02"),
  visual("vizual-03", "Vizual 03"),
  visual("vizual-03b", "Vizual 03B"),
  visual("vizual-04", "Vizual 04"),
  visual("vizual-04b", "Vizual 04B"),
  visual("vizual-05", "Vizual 05"),
  visual("vizual-06", "Vizual 06"),
  visual("vizual-07", "Vizual 07"),
  visual("vizual-08", "Vizual 08"),
  visual("vizual-09", "Vizual 09"),
  visual("vizual-10", "Vizual 10"),
  visual("vizual-11", "Vizual 11"),
  visual("vizual-12", "Vizual 12"),
  visual("vizual-13", "Vizual 13"),
];

export function vdockVisual(id: string | undefined | null): VdockVisual | undefined {
  if (!id) return undefined;
  return VDOCK_VISUALS.find((v) => v.id === id);
}
